# Generated by Django 4.0.3 on 2022-05-09 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('space_trip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('birthday', models.DateTimeField(verbose_name='data de nascimento')),
                ('gender', models.CharField(max_length=50)),
                ('planetionality', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=50)),
                ('origin', models.CharField(max_length=50)),
                ('departure_date', models.DateTimeField(verbose_name='Departure Date')),
                ('return_date', models.DateTimeField(verbose_name='Return Date')),
                ('price', models.IntegerField(default=600)),
                ('spaceship', models.CharField(max_length=50)),
                ('number_of_passengers', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space_trip.trip'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space_trip.purchase'),
        ),
    ]
