# Generated by Django 4.0.3 on 2022-05-09 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_trip', '0002_client_payment_purchase_trip_delete_aluno_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aluno',
        ),
    ]
