# Generated by Django 4.0.3 on 2022-05-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_trip', '0004_alter_purchase_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateTimeField(verbose_name='birthday'),
        ),
    ]
