# Generated by Django 4.0.3 on 2022-05-09 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('space_trip', '0007_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardName', models.CharField(max_length=50)),
                ('cardNumber', models.CharField(max_length=16)),
                ('expirationDate', models.DateTimeField(verbose_name='Expiration Date')),
                ('cvv', models.CharField(max_length=3)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space_trip.purchase')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
