# Generated by Django 4.0.3 on 2022-05-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_trip', '0008_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_pt', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=3000000000)),
            ],
        ),
    ]
