# Generated by Django 4.0.3 on 2022-05-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_trip', '0009_planets'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='available_seats',
            field=models.IntegerField(default=60),
        ),
    ]
