# Generated by Django 4.0.3 on 2022-05-12 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_trip', '0010_trip_available_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='available_seats',
        ),
        migrations.DeleteModel(
            name='Opcao',
        ),
        migrations.DeleteModel(
            name='Questao',
        ),
    ]
