# Generated by Django 4.0.3 on 2022-05-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_trip', '0011_alter_planets_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_pt', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=500000)),
            ],
        ),
        migrations.DeleteModel(
            name='Planets',
        ),
    ]
